### ISSUE TITLE
[TypeScript SDK] Add removeAllAddresses to SDK

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fiosdk_typescript#20]
Add the new removeAllAddresses call to the TypeScript SDK.

**Comment by edrotthoff** [comment]
the changes were made and placed into PR, https://github.com/fioprotocol/fiosdk_typescript/pull/21
this was reviewed by Andrew, who had 2 minor comments, these were addressed.

**Comment by ericbutz** [comment]
Build: release/v1.1.0
SDK: fiosdk_typescript/develop
Confirmed removeaddress.js ran cleanly against v1.1.0.
