### ISSUE TITLE
fetchJSON

### ISSUE THREAD

**Issue by alisajjad14** [fioprotocol/fiosdk_typescript#8]
In creating a FIO Object using FIO SDK, what is fetchJSON as I have to pass this parameter in the constructor of FIOSDK.ts

`/**
   * @param privateKey the fio private key of the client sending requests to FIO API.
   * @param publicKey the fio public key of the client sending requests to FIO API.
   * @param baseUrl the url to the FIO API.
   * @param fetchjson
   * @param registerMockUrl the url to the mock server
   * @param technologyProviderId Default FIO Address of the wallet which generates transactions.
   */
  constructor(
    privateKey: string,
    publicKey: string,
    baseUrl: string,
    fetchjson: FetchJson,
    registerMockUrl = '',
    technologyProviderId: string = '',
  ) {
    this.transactions = new Transactions()
    Transactions.baseUrl = baseUrl
    Transactions.FioProvider = Fio
    Transactions.fetchJson = fetchjson
    this.registerMockUrl = registerMockUrl
    this.privateKey = privateKey
    this.publicKey = publicKey
    this.technologyProviderId = technologyProviderId

    for (const accountName of Constants.rawAbiAccountName) {
      this.getAbi(accountName)
        .then((response) => {
          Transactions.abiMap.set(response.account_name, response)
        })
        .catch((error) => {
          throw error
        })
    }
  }`

There is no such document of fetchJSON explained the in the docs of FIO, Kindly explain its functionality and what value will be pass to this parameter in order to create its object.

**Comment by shawnarneygit** [comment]
Hi,

We will update the documentation, for this parameter.  What context are you using FIOSDK in.  For example, here is how to instantiate this parameter using 'node-fetch' as the HTTP module.

i.e.
fetch = require('node-fetch')

const fetchJson = async (uri, opts = {}) => {
  return fetch(uri, opts)
}

**Comment by alisajjad14** [comment]
@shawnarneygit I have already mentioned in my query that I am using it for domain creation and for that I need to first instantiate the constructor call of FIOSDK. what URI I will have to pass to fetchJSON? Kindly could you please explain this in detail?

**Comment by shawnarneygit** [comment]
You do not need to do anything else with fetchJson.

The Url is passed as a parameter to the FIOSDK constructor.

For code examples you can also look at the unit tests located here:
[https://github.com/fioprotocol/fiosdk_typescript/blob/master/tests/testnet.spec.js](https://github.com/fioprotocol/fiosdk_typescript/blob/master/tests/testnet.spec.js)

The readme.md file will specify how to work with testnet and the testnet url:
[https://github.com/fioprotocol/fiosdk_typescript/blob/master/README.md](https://github.com/fioprotocol/fiosdk_typescript/blob/master/README.md)

For your convenience, here is the complete example, of how to instantiate the SDK with the testnet url:
[https://github.com/fioprotocol/fiosdk_typescript/tree/develop/examples/RegisterFioAddress](https://github.com/fioprotocol/fiosdk_typescript/tree/develop/examples/RegisterFioAddress)
